[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SpaceTracer"
version = "2.1.1"
description = "A tool for calling mutations from spatial transcriptome data"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    { name = "Zhirui Yang" },
    { name = "Mengdie Yao" }
]
dependencies = [
    "PyYAML",
    "pandas",
    "numpy",
    "scipy",
    "pysam",
    "pyarrow",
    "scikit-learn",
    "joblib",
    "matplotlib",
    "seaborn",
    "tqdm",
    "psutil",
    "colorama",
    "pyfaidx",
    "biopython"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["SpaceTracer*"]

[tool.setuptools.package-data]
SpaceTracer = ["cores/*.R", "config/*.yaml", "installer/*.json", "resources/**/*", "models/**/*"]

[project.scripts]
spacetracer = "SpaceTracer.cli.main:main"

