#!/usr/bin/env python3

from pathlib import Path
from typing import Dict, List, Optional

from SpaceTracer.pipeline.dag import PipelineDAG
from SpaceTracer.pipeline.context_template import build_template_context
from SpaceTracer.pipeline.snake_render_utils import (
    flatten_output_dict,
    log_pattern,
    wildcard_flags_for_level,
)
from SpaceTracer.steps.registry import STEP_CLASSES


class DummyCheckpointManager:
    pass


class SnakemakeGenerator:
    """
    根据 DAG + BaseStep(get_outputs) 自动生成 Snakefile

    当前运行命令默认走 orchestrator only-step
    未来可切换为 step runner
    """

    def __init__(
        self,
        config: Dict,
        *,
        snakefile_path: str = "Snakefile",
        runner_mode: str = "orchestrator",   # orchestrator | step
        run_cli_module: str = "SpaceTracer.cli.run_pipeline",
        step_cli_module: str = "SpaceTracer.cli.run_step",
        final_step: Optional[str] = None,
    ):
        self.config = config
        self.snakefile_path = snakefile_path
        self.runner_mode = runner_mode
        self.run_cli_module = run_cli_module
        self.step_cli_module = step_cli_module
        self.dag = PipelineDAG()
        self.template_context = build_template_context(config)
        self.final_step = final_step or self._infer_final_step()

    def _infer_final_step(self) -> str:
        """
        默认取 topo plan 最后一个 step 作为 all rule 的最终目标
        """
        plan = self.dag.get_execution_plan()
        if not plan:
            raise ValueError("Pipeline DAG is empty")
        return plan[-1]

    def _get_step_instance(self, step_name: str):
        if step_name not in STEP_CLASSES:
            raise ValueError(f"Step '{step_name}' not found in STEP_CLASSES")
        step_cls = STEP_CLASSES[step_name]
        return step_cls(step_name, self.template_context.copy(), DummyCheckpointManager())

    def _get_step_outputs(self, step_name: str) -> Dict[str, str]:
        step = self._get_step_instance(step_name)
        outputs = step.get_outputs(self.template_context.copy())
        return outputs or {}

    def _get_step_file_outputs(self, step_name: str) -> List[str]:
        outputs = self._get_step_outputs(step_name)
        return flatten_output_dict(outputs)

    def _render_header(self) -> str:
        return '\n'.join([
            '# Auto-generated by SpaceTracer',
            'configfile: "config.yaml"',
            '',
        ])

    def _render_all_rule(self) -> str:
        final_outputs = self._get_step_file_outputs(self.final_step)
        if not final_outputs:
            raise ValueError(
                f"Final step '{self.final_step}' has no file outputs. "
                "Snakemake 'all' rule cannot be built."
            )

        lines = ['rule all:', '    input:']
        for p in final_outputs:
            lines.append(f'        "{p}",')
        lines.append('')
        return '\n'.join(lines)

    def _render_rule_input(self, step_name: str) -> List[str]:
        deps = self.dag.get_dependencies(step_name)
        if not deps:
            return ['    input:', '        []']

        lines = ['    input:']
        for dep_name in deps:
            dep_outputs = self._get_step_file_outputs(dep_name)
            if not dep_outputs:
                continue

            if len(dep_outputs) == 1:
                lines.append(f'        {dep_name}="{dep_outputs[0]}",')
            else:
                joined = ", ".join(f'"{x}"' for x in dep_outputs)
                lines.append(f'        {dep_name}=[{joined}],')
        return lines

    def _render_rule_output(self, step_name: str) -> List[str]:
        outputs = self._get_step_file_outputs(step_name)
        if not outputs:
            # 兜底：至少给一个 done 文件，避免无 output rule
            done_path = f'results/{{sample}}/.snakemake_done/{step_name}.done'
            return ['    output:', f'        done="{done_path}",']

        lines = ['    output:']
        if len(outputs) == 1:
            lines.append(f'        out="{outputs[0]}",')
        else:
            for i, p in enumerate(outputs, start=1):
                lines.append(f'        out{i}="{p}",')
        return lines

    def _build_shell_command(self, step_name: str) -> str:
        step = self.dag.steps[step_name]
        flags = wildcard_flags_for_level(step.run_level)

        if self.runner_mode == "orchestrator":
            cmd = [
                "python",
                "-m",
                self.run_cli_module,
                "--config",
                "config.yaml",
                "--only-step",
                step_name,
            ]
            cmd.extend(flags)
            return " ".join(cmd)

        elif self.runner_mode == "step":
            cmd = [
                "python",
                "-m",
                self.step_cli_module,
                "--config",
                "config.yaml",
                "--step",
                step_name,
            ]
            cmd.extend(flags)
            return " ".join(cmd)

        else:
            raise ValueError(f"Unsupported runner_mode: {self.runner_mode}")

    def _render_rule_log(self, step_name: str) -> List[str]:
        step = self.dag.steps[step_name]
        p = log_pattern(step_name, step.run_level)
        return ['    log:', f'        "{p}"']

    def _render_rule_shell(self, step_name: str) -> List[str]:
        cmd = self._build_shell_command(step_name)
        lines = [
            '    shell:',
            '        """',
            '        mkdir -p $(dirname {log})',
            f'        {cmd} > {{log}} 2>&1',
            '        """',
        ]
        return lines

    def _render_rule(self, step_name: str) -> str:
        lines = [f'rule {step_name}:']
        lines.extend(self._render_rule_input(step_name))
        lines.extend(self._render_rule_output(step_name))
        lines.extend(self._render_rule_log(step_name))
        lines.extend(self._render_rule_shell(step_name))
        lines.append('')
        return '\n'.join(lines)

    def render(self) -> str:
        plan = self.dag.get_execution_plan()
        parts = [
            self._render_header(),
            self._render_all_rule(),
        ]

        for step_name in plan:
            parts.append(self._render_rule(step_name))

        return '\n'.join(parts)

    def write(self) -> str:
        text = self.render()
        Path(self.snakefile_path).write_text(text, encoding="utf-8")
        return self.snakefile_path
