# SpaceTracer Default Configuration

# input (for visium, not contain HD data)
genome: hg38
resource_dir: # if provided, all resource will be found in the directory
sequence_type: visium # choice: visium, stereo-seq, ST, visium-HD
bin_size: # only work for stereo-seq data. If use stereo-seq data, the cluster file must be provided!
spaceranger_dir: # Please provide the "{prefix}/outs" dir. If None or not provided, please give the bam file and tissue_position file 
regions_file: /storage/douyanmeiLab/yangzhirui/01.Data_download/Callable_region_compare/all_callable_merge.bed
output_dir: /storage/douyanmeiLab/yangzhirui/SpaceTracer_new/

input_details: # if visium data and spaceranger dir have been provided, the following could be ignored
  bam_file: 
  tissue_position: 
  barcode_key: # this may not work for stereo-seq

resource_details: # if resource dir provided, the below config could be ignored, or each would be 
  genome_fasta: /storage/douyanmeiLab/yangzhirui/Reference/Cellranger/refdata-gex-GRCh38-2020-A/fasta/genome.fa
  gnomad_path: /storage/douyanmeiLab/yangzhirui/Reference/resource/only_af/ 
  mappability_path: /storage/douyanmeiLab/yangzhirui/Reference/MapScore_umap_multiRead/k24.umap.bedgraph
  gene_bed: /storage/douyanmeiLab/yangzhirui/Reference/gtexGene.txt
  dbsnp_vcf_file: /storage/douyanmeiLab/yangzhirui/Reference/dbSNP/Homo_sapiens_assembly38.dbsnp138.vcf
  imprinted_bed: /storage/douyanmeiLab/yangzhirui/Reference/Cellranger/refdata-gex-GRCh38-2020-A/imprinted_genes.region.bed
  editing_bed: /storage/douyanmeiLab/yangzhirui/Reference/COMBINED_RADAR_REDIprotal_DARNED_hg38_all_sites.bed
  PON_file: /storage/douyanmeiLab/yangzhirui/01.Data_download/PON/PON_new_model_250921_33samples_251224.only_sites.txt
  reference_error_profile: /storage/douyanmeiLab/yangzhirui/01.Data_download/Mutation_signatures_new_creteria/use_not_validated_low_freq_001_251021/lysis_Signatures_split3.Sigprofile.txt

run:
  threads: 20 
  memory: "200G"
  max_parallel: 40
  keep_intermediates: true # all intermediate files will be exported as files
  skip_validation: true
  
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_file: "pipeline.log"

# Step-specific configurations (optional)
steps:
  # Step 0: Cluster [if not provided, the cluster function will run]
  cluster:
    cluster_file:  # [if provided, the cluster function will be ignored]
    ncluster: 8
    plot: true
    method: "SpaGCN"          # 原 --method
    init_method: "louvain"    # 原 --init_method
    data_type: "Visium" 
    h5_file_name: "filtered_feature_bc_matrix.h5"
    histology: true
    spot_area: 49             # 原 --b，改成更清晰的名字
    weight_histology: 1
    distance_threshold: 2
    min_samples: 1
    num_threshold: 30
    percentage: 0.5           # 原 --pertentage（修正拼写）
    seed: 100
    tol: 5e-3
    lr: 0.05
    max_epochs: 200           # 原 --max_epochs_run
    # GraphST 专用
    graphst_tool: "louvain"   # 原 --tool
    radius: 6
    refinement: true

  # Step 1: BAM Processing
  bam_processing:
    nm_threshold: 5
    mapq_threshold: 255
  
  # Step 2: Mpileup
  mpileup:
    min_depth: 30 # strongly recommended
    max_depth: 200000 # strongly recommended
    min_mapq: 0
    min_baseq: 0
    exclude_flag:  0 # strongly recommended
    enable_split: True
    split_threshold: 4000
    chrom_chunk_size: 2000
    chrM_chunk_size: 100

  # Step 3 Calculate cell number (optional)
  cell_number: 
  
  # Step 3: UMI combine
  UMI_combine:
    filter_duplicates: true
    filter_secondary: true
    filter_qcfail: true
    filter_supplementary: true
    min_read_quality: 20
    extract_features:
      - "base_quality"
      - "mapping_quality"
      - "strand"
      - "position_in_read"
  
  # Step 5: Genotyping
  genotyping:
    alpha: 0.05
    epsQ: 20
    epsAF: 0.003
    mu: 1e-5
    thr_dp: 1000
    pop_vaf: 1e-5
    filter_oneallele: True

  spatial_feature:
    alpha: 0.05
    thr_r2: 0.3
    thr_prob: 0.9
    thr_likelihood: 0.9
    thr_vaf: 0
    plot_supp: False
    fig_size: 5
    method: LDA
    num_directions: 8

  read_feature:
    cell_info: None 
    downsample: True
    downsample_target_depth: 2000
    max_region_size: 20000
    max_variants_per_region: 100
    seed: 42
    
  RNA_feature:
    min_count_for_germline: 50
    min_prior_for_germline: 0.0001
    default_range_of_gene: 150
    p_threshold: 0.05
    previous_base: 5

  feature_filtration:
      ASE: True
      hFDR: True
      imprinted: True
      homopolymer: True
      PON: True
      RNA_editing: True
      ABNORMAL_MISMATCHES: True
      LOW_READ_DIVERSITY: True
      HIGH_MULTIPLE_MAPPIN: True
      WIDE_DISTRIBUTION: True
      NEAR_READ_END: True
